git:
  commitMessage: 'Release v${version}'
  requireUpstream: false
  tag: true
  push: true

npm:
  publish: true

hooks:
  before:init:
    - git checkout main
    - git pull --rebase
    - npm install
    - npm run lint
    - npm run test
    - npm run audit
  before:bump:
    - npm run docs
